### ISSUE TITLE
clarification avant / après / to_merge

### ISSUE THREAD

**Issue by parmentelat** [flotpython/gittutorial#2]
@giliam 

> #8, idem, je ne comprends pas bien le graphe, ce que représentent les avant, après, le to_merge... :S

> Je parlais de ça : https://flotpython-gittutorial.readthedocs.io/fr/latest/2-04-kinds-of-merge.exec.html#id1

**Comment by parmentelat** [comment]
dans les deux cas la figure montre
. la branche courante `current` avant et après le merge
. lorsqu'on merge `to_merge`

le coin en haut à droite est juste la légende qui dit que le `current` en vert est la branche courante avant le merge, pareil pour bleu

**Comment by giliam** [comment]
Ah ok, j'ai enfin compris. --" C'était pourtant pas si bête mais c'est vrai
que la situation de droite où il n'y pas de merge n'est pas une situation
que je rencontre souvent alors je ne parvenais pas à bien suivre :D

Le jeu. 8 août 2019 à 06:30, parmentelat <notifications@github.com> a
écrit :

**Comment by parmentelat** [comment]
une fois qu'on a dit ça, si ça n'était pas clair pour toi à la première lecture c'est qu'il y a de la place pour améliorer, j'ai tenté quelque chose avec 02b936b2f4699b7d602de19d5971aa6ec3d962ac

**Comment by giliam** [comment]
Bien plus clair, en effet ! :)
