### ISSUE TITLE
duplicats notebooks/foo.ipynb et notebooks/exporting/foo.exec.ipynb

### ISSUE THREAD

**Issue by parmentelat** [flotpython/gittutorial#4]
@giliam 

la première expérience de pull request a montré que les duplicats de notebooks 'exécutés' étaient plus confusants qu'autre chose

je viens de faire un essai pour se débarrasser de cette surcouche qui n'était là que pour éviter  de faire tourner les notebooks sur readthedocs; et en fait ça marche très bien de les exécuter dans readthedocs, donc on va pouvoir se débarrasser de ce hack

**Comment by giliam** [comment]
My bad, je n'ai même pas fait attention que je modifiais deux dossiers différents. Tant mieux si ça marche sans ! Merci :)
